  server:
    port: 2021
  #  serverTimeZone=UTC&
  spring:
    datasource:
      username: root
      password: as112066
      url: jdbc:mysql://localhost:3306/jsoup?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    servlet:
      multipart:
        max-file-size: 10MB
    mail:
      host: smtp.qq.com #发送邮件服务器
      username: mmmmmmm #发送邮件的邮箱地址
      password: mmmmmmm #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
      properties.mail.smtp.port: 465 #端口号465或587
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8

  mybatis:
    type-aliases-package: dam.jsoup.updatereport.updatereport.pojo
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
  #logging:
  #  file:
  #    name: spring-boot.log
  #  pattern:
  #    console: "%d{yyyy-MM-dd} [ %thread ] - [ %-5level ] [ %logger{50} : %line ] - %msg%n"
  #    file: "%d{yyyy-MM-dd} [ %thread ] - [ %-5level ] [ %logger{50} : %line ] - %msg%n"
